
project_id = "hchmfsilgfrzhenafbzi"

[functions.send-email]
verify_jwt = true

[functions.scan-receipt]
verify_jwt = true

[functions.generate-recurring-expenses]
verify_jwt = false

[functions.delete-tenant]
verify_jwt = true

[functions.remove-tenant-member]
verify_jwt = true

[functions.get-user-emails]
verify_jwt = false

[functions.add-tenant-member]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-sms]
verify_jwt = false

[functions.verify-sms-code]
verify_jwt = false

[functions.complete-family-registration]
verify_jwt = false
